### ISSUE TITLE
numbers containing billions are pronnounced incorrectly

### ISSUE THREAD

**Issue by beqabeqa473** [poretsky/ru_tts#10]
hello.

There is a bug in number declination, specifically when we are writing numbers like 5000000000 Пять миллиардов, 3000000000 Три миллиарда, ru_tts reads numbers as Пять миллиартов, Три миллиарта, because in transcription Миллиард is written as Миллиарт, and when adding suffixes, т is not replaced by д

**Comment by electrik-spb** [comment]
Подтверждаю, есть такой баг.
