### ISSUE TITLE
Speech rate variation range

### ISSUE THREAD

**Issue by poretsky** [poretsky/ru_tts#2]
It seems to be desirable to increase upper limit of speech rate.

**Comment by beqabeqa473** [comment]
Hello @poretsky.

While using ru_tts on a daily bases, me and people who listens to the synthesizer at higher rates noticed that ru_tts is not as fast in terms of speech rate as we might like to have.

I understand that at higher rates, synthesizer can be crackling, but if it is possible, could you please look at this issue?
Maybe if you don't want to increase rate with main adjust mechanism, it would be possible to make a flag like rate boost, which shifts frames in the table or something like that.


Thanks for your work.
