### ISSUE TITLE
Unicode input

### ISSUE THREAD

**Issue by poretsky** [poretsky/ru_tts#3]
Input text should be accepted in UTF8 since it is an ubiquitous standard.

**Comment by beqabeqa473** [comment]
Hello @poretsky.

Is there any progress in this area?

I am starting to port rutts to one of mobile platforms and before i do recoding myself, i wanted to ask as there is an issue opened.

Thanks.

**Comment by poretsky** [comment]
No progress.

When I ported it to Android in the context of SmartVoice some years ago,
I've merely made a simple recoding table.

**Comment by poretsky** [comment]
Actually resolved in 1841da1aafa6edd8e800a9bede74977710300a0f
