### ISSUE TITLE
Transliteration

### ISSUE THREAD

**Issue by poretsky** [poretsky/ru_tts#5]
For latin letters the following transliteration rules should be
implemented:

j=дж
q=ку
w=в
x=кс

**Comment by poretsky** [comment]
Implemented in https://github.com/poretsky/multispeech/commit/39476c9252ffb2b289b686140bc004acfb31ba8e

**Comment by beqabeqa473** [comment]
It is great that this was implemented in multispeech but ru_tts is used more widely than multispeech on other platforms, so i think it is reasonable to fix that in the core rather than reinventing the wheel for each product which includes ru_tts.

**Comment by poretsky** [comment]
But personally I treat it mainly as a backend for the other
applications, such as Multispeech or SmartVoice that take care of text
preparation itself. Thus, I do not plan to implement it here.
