### ISSUE TITLE
data voice file?

### ISSUE THREAD

**Issue by zvezdochiot** [poretsky/ru_tts#9]
Hi @poretsky .

Интересует возможность замены `male.c` и `female.c` на отдельные от синтезатора файлы голосов. Например, как в https://github.com/Geo-Linux-Calculations/egm96 файлы моделей геоида являются внешними и читаются утилитами при запуске.

**Comment by poretsky** [comment]
Теоретически, такую возможность обеспечить несложно. Но зачем? Где
файлы-то брать?

**Comment by zvezdochiot** [comment]
Hi @poretsky .

Ну раньше у RHVoice тоже всего то ничего было. А теперь со всех щелей, как из рога изобилия лезут. Вопрос не в том, что откуда брать, а в том, что существующие (male, female) можно модифицировать без перекомпиляции тулзы.

**Comment by poretsky** [comment]
Если Вы располагаете реальными технологиями для такой модификации,
большая просьба поделиться. В противном случае это пустые разговоры.

**Comment by zvezdochiot** [comment]
Hi @poretsky .

335... В RHVoice тоже таких "технологий" нема.... :))) Пустой разговор, говоришь?
>можно модифицировать без перекомпиляции тулзы.
(уже определённая технология, "метод научного подгона).

**Comment by poretsky** [comment]
Ошибаетесь. RHVoice *построен* на такой технологии.

**Comment by zvezdochiot** [comment]
Hi @poretsky .

Не ошибаюсь. Теперь есть. Изначально не "есть".
